apiVersion: v1	
kind: Service
metadata:
  labels:
    app: flask
  name: flaskapp
  namespace: flaskapp-dev
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: flask
  type: LoadBalancer
