apiVersion: v1
kind: Service
metadata:
  labels:	
    app.kubernetes.io/instance: redis
  name: redis-deployment	
  namespace: default	
  selfLink: /api/v1/namespaces/default/services/redis-deployment	
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:	
    app: redis
  type: LoadBalancer
